### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by rtutin**

### CODE REVIEW

**Comment by Rivsen** [comment]
因为很多人对composer如何加载一个单独的类文件比较迷惑，所以我的demo里是使用类和命名空间来做的，如果是function，那么composer的自动加载就不是psr4了，而是通过files的方式，这个要是写，又能啪啦啪啦写一大篇了。

Demo：

"autoload": {
        "psr-4": { "Rivsen\Demo\": "src" },
        "files": ["src/functions.php"]
    }

composer update

然后引入autoload.php就可以随处使用functions.php里的函数了。

**Comment by Rivsen** [comment]
另外还是谢谢你的PR，我这里的test做的不是很好，应该做成phpunit的单元测试脚本就对了，我临时兴起写了那个test.php，玩起来简单一些～

**Comment by rtutin** [comment]
I'm not understand on asian langs, lol

**Comment by Rivsen** [comment]
Sorry for that.

This demo is a composer tutorial's demo code, I use OOP in demo because many people ask about how to load custom class or libs into a composer managed project. I will write some tutorial for composer's autoload knowledge in the coming days. And thank you for your PR!

PS: These tutorials are published on my GitHub Pages: https://rivsen.github.io , but in Chinese~

**Pull request closed without merging**
